import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { cn } from '@/lib/utils'
import { SiteHeader } from '@/components/site-header'

const inter = Inter({ subsets: ['latin'] })
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <div className="flex h-screen flex-col">
      <SiteHeader />
      <main className="flex w-full flex-1 justify-center px-5 pb-16 pt-8">{children}</main>
    </div>
  )
}
