import type { Metadata } from 'next'
import { guminert } from '@/themes/fonts'
import { cn } from '@/lib/utils'

import './globals.css'

export const metadata: Metadata = {
  title: 'Entry Jobs',
  description: 'Generated by create next app',
}

const RootLayout = ({ children }: { children: React.ReactNode }) => (
  <html lang="en" className="h-full w-full">
    <head />
    <body
      className={cn(
        guminert.variable,
        'text- max-h-screen min-h-screen max-w-full bg-background font-sans text-foreground antialiased',
      )}
    >
      {children}
    </body>
  </html>
)
export default RootLayout
