/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/fHWwOw4V3QD
 */
import { CardTitle, CardDescription, CardHeader, CardContent, CardFooter, Card } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { SelectValue, SelectTrigger, SelectItem, SelectContent, Select } from "@/components/ui/select"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"

export function Component() {
  return (
    <div key="1" className="bg-white min-h-screen">
      <div className="flex justify-between items-center p-6">
        <ArrowLeftIcon className="text-gray-600" />
        <div className="flex space-x-2">
          <div className="bg-gray-200 w-2 h-2 rounded-full" />
          <div className="bg-gray-400 w-2 h-2 rounded-full" />
          <div className="bg-gray-400 w-2 h-2 rounded-full" />
        </div>
        <div />
      </div>
      <div className="max-w-4xl mx-auto px-6">
        <h1 className="text-4xl font-bold text-gray-800 mb-6">
          Onboarding
          <h2 className="text-2xl font-semibold text-gray-600 mt-2">
            Choose your own adventure! Import jobs from email or set up a custom job query. Or, why not both?
          </h2>
        </h1>
        <div className="grid grid-cols-2 gap-8">
          <Card className="w-full rounded-lg">
            <CardHeader>
              <CardTitle>Import Jobs from Email</CardTitle>
              <CardDescription>
                Connect your email provider to import job postings directly into your dashboard.
              </CardDescription>
            </CardHeader>
            <CardContent>
              <form>
                <div className="grid w-full items-center gap-4">
                  <div className="flex flex-col space-y-1.5">
                    <Label htmlFor="email-provider">Email Provider</Label>
                    <Select>
                      <SelectTrigger id="email-provider">
                        <SelectValue placeholder="Select email provider" />
                      </SelectTrigger>
                      <SelectContent position="popper">
                        <SelectItem value="gmail">Gmail</SelectItem>
                        <SelectItem value="outlook">Outlook</SelectItem>
                        <SelectItem value="yahoo">Yahoo Mail</SelectItem>
                        <SelectItem value="other">Other</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>
                </div>
              </form>
            </CardContent>
            <CardFooter className="flex justify-end">
              <Button variant="outline">Skip</Button>
              <Button>Connect</Button>
            </CardFooter>
          </Card>
          <Card className="w-full rounded-lg">
            <CardHeader>
              <CardTitle>Setup Custom Job Query</CardTitle>
              <CardDescription>Create a custom query to search across multiple job boards.</CardDescription>
            </CardHeader>
            <CardContent>
              <form>
                <div className="grid w-full items-center gap-4">
                  <div className="flex flex-col space-y-1.5">
                    <Label htmlFor="job-title">Job Title</Label>
                    <Input id="job-title" placeholder="e.g., Junior Developer" />
                  </div>
                  <div className="flex flex-col space-y-1.5">
                    <Label htmlFor="location">Location</Label>
                    <Input id="location" placeholder="e.g., San Francisco, CA" />
                  </div>
                </div>
              </form>
            </CardContent>
            <CardFooter className="flex justify-end">
              <Button variant="outline">Skip</Button>
              <Button>Search</Button>
            </CardFooter>
          </Card>
        </div>
      </div>
    </div>
  )
}


function ArrowLeftIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m12 19-7-7 7-7" />
      <path d="M19 12H5" />
    </svg>
  )
}
